{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4f123add",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import os\n",
    "import jaydebeapi\n",
    "import jpype\n",
    "from datetime import datetime\n",
    "from dateutil.relativedelta import relativedelta\n",
    "from dotenv import load_dotenv, find_dotenv\n",
    "import warnings\n",
    "\n",
    "warnings.filterwarnings(\"ignore\")\n",
    "load_dotenv(find_dotenv())\n",
    "\n",
    "# ================================\n",
    "# CONFIG\n",
    "# ================================\n",
    "campaign_year = 2026\n",
    "campaign_month = 4\n",
    "\n",
    "data_date = datetime(campaign_year, campaign_month, 1) - relativedelta(months=1)\n",
    "data_month = data_date.month\n",
    "data_year = data_date.year\n",
    "\n",
    "start_of_month = datetime(data_year, data_month, 1)\n",
    "end_of_month = start_of_month + relativedelta(months=1) - relativedelta(days=1)\n",
    "\n",
    "start_ts = start_of_month.strftime(\"%Y-%m-%d 00:00:00\")\n",
    "end_ts = end_of_month.strftime(\"%Y-%m-%d 23:59:59\")\n",
    "\n",
    "today = datetime.today()\n",
    "current_start = datetime(today.year, today.month, 1)\n",
    "current_end = current_start + relativedelta(months=1) - relativedelta(days=1)\n",
    "current_next = current_start + relativedelta(months=1)\n",
    "\n",
    "vpodsa_date_current = current_end.strftime(\"%Y%m%d\")\n",
    "vpadsa_next_current = current_next.strftime(\"%Y%m%d\")\n",
    "\n",
    "print(\"\\n================ CONFIG: Brussels ================\")\n",
    "print(\"Campaign month:\", campaign_month)\n",
    "print(\"Data month:\", data_month)\n",
    "print(\"DB snapshot month:\", today.month)\n",
    "\n",
    "# ================================\n",
    "# HELPERS\n",
    "# ================================\n",
    "def anatella_cast(series):\n",
    "    return (\n",
    "        pd.to_numeric(series, errors=\"coerce\")\n",
    "        .dropna()\n",
    "        .astype(int)\n",
    "        .astype(str)\n",
    "    )\n",
    "\n",
    "def normalize_exid(x):\n",
    "    if pd.isna(x):\n",
    "        return None\n",
    "    try:\n",
    "        return str(int(str(x).strip()))\n",
    "    except:\n",
    "        return None\n",
    "\n",
    "def clean_exid(series):\n",
    "    return (\n",
    "        series.apply(lambda x: ''.join(x) if isinstance(x, tuple) else str(x))\n",
    "        .str.strip()\n",
    "    )\n",
    "\n",
    "# ================================\n",
    "# CONNECTION\n",
    "# ================================\n",
    "def connect():\n",
    "    jar_path = r\"C:\\db2\\db2jcc4.jar\"\n",
    "    if not jpype.isJVMStarted():\n",
    "        jpype.startJVM(\n",
    "            jpype.getDefaultJVMPath(),\n",
    "            \"-Xmx2g\",\n",
    "            \"-Djava.class.path=\" + jar_path\n",
    "        )\n",
    "    return jaydebeapi.connect(\n",
    "        \"com.ibm.db2.jcc.DB2Driver\",\n",
    "        \"jdbc:db2://s998lp1dbbi01.jablux.cpc998.be:50004/ods500\",\n",
    "        [\"m509psao\", os.getenv(\"DB_PASSWORD\")]\n",
    "    )\n",
    "\n",
    "conn = connect()\n",
    "\n",
    "# ================================\n",
    "# DB QUERY\n",
    "# ================================\n",
    "query = f\"\"\"\n",
    "SELECT p.EXIDSA, p.PROVSA, v.VPV1SV, p.NAIDSA,\n",
    "CASE WHEN s.EXIDSA IS NOT NULL THEN 1 ELSE 0 END AS OPT_OUT_FLAG\n",
    "FROM ODS509.ODS_PSTATA p\n",
    "LEFT JOIN ODS509.ODS_PSTATV v ON p.EXIDSA = v.EXIDSV\n",
    "LEFT JOIN (\n",
    "    SELECT DISTINCT REPLACE(TARGETID, ',', '') AS EXIDSA\n",
    "    FROM ODS509.V_ISE_ODS_WWWSIGNAL\n",
    "    WHERE SIGNALID = 'CampagneCC' AND INACTIVE = 0\n",
    ") s ON p.EXIDSA = s.EXIDSA\n",
    "WHERE (\n",
    "    p.VPODSA >= {vpodsa_date_current}\n",
    "    AND p.VPACSA <> 'O'\n",
    "    AND (\n",
    "        (p.VPACSA = 'T' AND p.VPADSA <= {vpadsa_next_current})\n",
    "        OR (\n",
    "            p.VPACSA IN ('A','B','C','L')\n",
    "            AND p.VPADSA < {vpadsa_next_current}\n",
    "        )\n",
    "    )\n",
    "    AND p.IV00SA = 'B'\n",
    ")\n",
    "\"\"\"\n",
    "\n",
    "df = pd.read_sql(query, conn)\n",
    "df.columns = [str(c).upper() for c in df.columns]\n",
    "\n",
    "print(\"\\nDB RAW:\", len(df), \"| Unique:\", df[\"EXIDSA\"].nunique())\n",
    "\n",
    "# ================================\n",
    "# CLEAN DB\n",
    "# ================================\n",
    "df[\"EXID\"] = df[\"EXIDSA\"].astype(str).str.strip()\n",
    "df[\"VPV1SV\"] = df[\"VPV1SV\"].astype(str)\n",
    "\n",
    "df = df[\n",
    "    (df[\"VPV1SV\"] >= \"000\") &\n",
    "    ((df[\"VPV1SV\"] < \"750\") | (df[\"VPV1SV\"] > \"755\"))\n",
    "]\n",
    "\n",
    "df = df.groupby(\"EXID\", as_index=False).agg({\n",
    "    \"PROVSA\": \"first\",\n",
    "    \"VPV1SV\": \"first\",\n",
    "    \"OPT_OUT_FLAG\": \"max\",\n",
    "    \"NAIDSA\": \"first\"\n",
    "})\n",
    "\n",
    "print(\"DB FINAL (after filtering VPV1SV >= 000  && (VPV1SV < 750 || VPV1SV > 755):\", len(df))\n",
    "\n",
    "# ================================\n",
    "# POP\n",
    "# ================================\n",
    "pop = pd.read_excel(r\"C:\\Users\\M509PSAO\\Desktop\\EXIDs\\POP_ELIGIBLE_PARTENAMUT_2026_NEW.xlsx\")\n",
    "pop[\"EXID\"] = anatella_cast(pop[\"EXID\"])\n",
    "pop = pop.drop_duplicates(\"EXID\")\n",
    "\n",
    "print(\"POP:\", len(pop))\n",
    "\n",
    "# ================================\n",
    "# BASE\n",
    "# ================================\n",
    "base = pop.merge(df, on=\"EXID\", how=\"inner\")\n",
    "\n",
    "# ================================\n",
    "# Filter out Brussels prov and opted out members\n",
    "# ================================\n",
    "\n",
    "base = base[\n",
    "    (pd.to_numeric(base[\"PROVSA\"], errors=\"coerce\") == 10) &\n",
    "    (pd.to_numeric(base[\"OPT_OUT_FLAG\"], errors=\"coerce\") == 0)\n",
    "]\n",
    "\n",
    "print(\"BASE FILTERED (after join with my Mymut file and removed opted out members and filtered on provence):\", len(base))\n",
    "\n",
    "base[\"MOIS_NAISS\"] = base[\"NAIDSA\"].astype(str).str[4:6].astype(int)\n",
    "\n",
    "# ================================\n",
    "# MYMUT (ENRICHMENT ONLY)\n",
    "# ================================\n",
    "mymut = pd.read_excel(\n",
    "    r\"C:\\Users\\M509PSAO\\Desktop\\EXIDs\\Mymut_accounts_03.xlsx\",\n",
    "    usecols=[\"EXTERNAL_ID\", \"MMT_HAS_MYMUT_ACCOUNT_ISACTIVE_CNT\"]\n",
    ")\n",
    "\n",
    "mymut = mymut[mymut[\"MMT_HAS_MYMUT_ACCOUNT_ISACTIVE_CNT\"] == 1]\n",
    "mymut[\"EXTERNAL_ID\"] = anatella_cast(mymut[\"EXTERNAL_ID\"])\n",
    "mymut = mymut.drop_duplicates(\"EXTERNAL_ID\")\n",
    "\n",
    "print(\"Mymut count:\", len(mymut))\n",
    "\n",
    "\n",
    "base[\"EXID\"] = base[\"EXID\"].astype(str).str.strip()\n",
    "mymut[\"EXTERNAL_ID\"] = mymut[\"EXTERNAL_ID\"].astype(str).str.strip()\n",
    "\n",
    "base = base.merge(\n",
    "    mymut[[\"EXTERNAL_ID\"]],\n",
    "    left_on=\"EXID\",\n",
    "    right_on=\"EXTERNAL_ID\",\n",
    "    how=\"left\"\n",
    ").drop(columns=[\"EXTERNAL_ID\"])\n",
    "\n",
    "# ================================\n",
    "# EBOX READ\n",
    "# ================================\n",
    "ebox_read = pd.read_sql(\"\"\"\n",
    "SELECT DISTINCT BENEFICIARYEXID\n",
    "FROM ODS509.V_INF_ODS_DOCUMENT\n",
    "WHERE ORGANIZATION = '509'\n",
    "AND \"READ\" = 1\n",
    "AND OUTPUTCHANNELS = 'infobox'\n",
    "AND READDATE >= ADD_MONTHS(CURRENT_DATE, -18)\n",
    "AND READDATE < DATE '9999-01-01'\n",
    "\"\"\", conn)\n",
    "\n",
    "ebox_read[\"user_exid\"] = clean_exid(ebox_read[\"BENEFICIARYEXID\"])\n",
    "ebox_read[\"user_exid\"] = anatella_cast(ebox_read[\"user_exid\"])\n",
    "ebox_read[\"user_exid\"] = ebox_read[\"user_exid\"].apply(normalize_exid)\n",
    "ebox_read[\"user_exid\"] = ebox_read[\"user_exid\"].str.upper()\n",
    "\n",
    "print(\"READ count:\", len(ebox_read))\n",
    "\n",
    "# ================================\n",
    "# NOT READ\n",
    "# ================================\n",
    "not_read = pd.read_sql(f\"\"\"\n",
    "SELECT DISTINCT BENEFICIARYEXID\n",
    "FROM ODS509.V_INF_ODS_DOCUMENT\n",
    "WHERE ORGANIZATION = '509'\n",
    "AND \"READ\" = 0\n",
    "AND RECEIVEDATE BETWEEN TIMESTAMP '{start_ts}' AND TIMESTAMP '{end_ts}'\n",
    "AND NAME LIKE 'NMKTCBI%'\n",
    "AND NOTIFICATIONREQUESTSTATUS = 'DELIVERED'\n",
    "\"\"\", conn)\n",
    "\n",
    "not_read[\"EXID\"] = clean_exid(not_read[\"BENEFICIARYEXID\"])\n",
    "not_read[\"EXID\"] = anatella_cast(not_read[\"EXID\"])\n",
    "not_read[\"EXID\"] = not_read[\"EXID\"].apply(normalize_exid)\n",
    "not_read[\"EXID\"] = not_read[\"EXID\"].str.upper()\n",
    "not_read = not_read[[\"EXID\"]].drop_duplicates()\n",
    "\n",
    "print(\"NOT READ count:\", len(not_read))\n",
    "\n",
    "# ================================\n",
    "# NORMALIZATION\n",
    "# ================================\n",
    "base[\"EXID\"] = base[\"EXID\"].apply(normalize_exid).str.upper()\n",
    "\n",
    "# ================================\n",
    "# VISITED / NOT VISITED\n",
    "# ================================\n",
    "ebox_active_exids = set(ebox_read[\"user_exid\"])\n",
    "\n",
    "visited = base[base[\"EXID\"].isin(ebox_active_exids)].drop_duplicates(\"EXID\")\n",
    "not_visited = base[~base[\"EXID\"].isin(ebox_active_exids)].drop_duplicates(\"EXID\")\n",
    "\n",
    "# ================================\n",
    "# MONTH FILTER\n",
    "# ================================\n",
    "visited_month = visited[visited[\"MOIS_NAISS\"] == data_month][[\"EXID\"]]\n",
    "not_visited_month = not_visited[not_visited[\"MOIS_NAISS\"] == data_month][[\"EXID\"]]\n",
    "\n",
    "print(\"NOT VISITED:\", len(not_visited_month))\n",
    "print(\"VISITED:\", len(visited_month))\n",
    "\n",
    "# ================================\n",
    "# FINAL LOGIC (NO DUPLICATES)\n",
    "# ================================\n",
    "paper_send_total = pd.concat([\n",
    "    not_visited_month,\n",
    "    not_read\n",
    "]).drop_duplicates(subset=[\"EXID\"])\n",
    "\n",
    "# ================================\n",
    "# VALIDATION\n",
    "# ================================\n",
    "print(\"\\n================ VALIDATION ================\")\n",
    "print(\"BASE (after join with my Mymut and removed opted out members and filtered on provence):\", len(base))\n",
    "print(\"eBox send:\", len(visited_month))\n",
    "print(\"Paper send:\", len(paper_send_total))\n",
    "print(\"  -- NO EBOX:\", len(not_visited_month))\n",
    "print(\"  -- NOT READ:\", len(not_read))\n",
    "\n",
    "# ================================\n",
    "# EXPORT\n",
    "# ================================\n",
    "export_path = r\"C:\\Users\\M509PSAO\\Desktop\\EXIDs\"\n",
    "\n",
    "visited_month.to_excel(\n",
    "    os.path.join(export_path, \"Bruxelles_eBox_Send_April_2026.xlsx\"),\n",
    "    index=False\n",
    ")\n",
    "\n",
    "paper_send_total.to_excel(\n",
    "    os.path.join(export_path, \"Bruxelles_Paper_Send_April_2026.xlsx\"),\n",
    "    index=False\n",
    ")\n",
    "\n",
    "print(\"Export completed successfully.\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": ".venv (3.11.9)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
